In [1]:
import pandas as pd
import numpy as np
import re
import traceback
import sys
from variables import * 
import tqdm
import json

In [2]:
df = pd.read_csv('dataset/Influenza_Vaccination_Coverage.csv')
df.head()

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
0,Seasonal Influenza,Counties,New Haven,9009,2018,1,>=18 Years,Non-Medical Setting,45.5,43.9 to 47.2,NaN
1,Seasonal Influenza,Counties,New Haven,9009,2021,1,>=18 Years,Non-Medical Setting,53.0,46.0 to 60.9,NaN
2,Seasonal Influenza,Counties,New Haven,9009,2020,1,Age,>=18 Years,52.4,50.6 to 54.3,NaN
3,Seasonal Influenza,Counties,New Haven,9009,2021,1,Age,>=18 Years,50.2,45.4 to 55.8,NaN
4,Seasonal Influenza,Counties,New Haven,9009,2018,1,Age,>=18 Years,34.0,32.6 to 35.5,NaN

In [3]:
df['Vaccine'].unique()

array(['Seasonal Influenza',
       'Any Influenza Vaccination, Seasonal or H1N1',
       'Influenza A (H1N1) 2009 Monovalent'], dtype=object)

In [4]:
df.shape[0]

220729

In [5]:
# clean the vaccines first
df['Vaccine'] = df['Vaccine'].replace('Seasonal Influenza', 'Influenza')
df.head()

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
0,Influenza,Counties,New Haven,9009,2018,1,>=18 Years,Non-Medical Setting,45.5,43.9 to 47.2,NaN
1,Influenza,Counties,New Haven,9009,2021,1,>=18 Years,Non-Medical Setting,53.0,46.0 to 60.9,NaN
2,Influenza,Counties,New Haven,9009,2020,1,Age,>=18 Years,52.4,50.6 to 54.3,NaN
3,Influenza,Counties,New Haven,9009,2021,1,Age,>=18 Years,50.2,45.4 to 55.8,NaN
4,Influenza,Counties,New Haven,9009,2018,1,Age,>=18 Years,34.0,32.6 to 35.5,NaN

In [6]:
df['Sample Size'] = pd.to_numeric(df['Sample Size'], errors='coerce').astype('Int64')
df.head()

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
0,Influenza,Counties,New Haven,9009,2018,1,>=18 Years,Non-Medical Setting,45.5,43.9 to 47.2,<NA>
1,Influenza,Counties,New Haven,9009,2021,1,>=18 Years,Non-Medical Setting,53.0,46.0 to 60.9,<NA>
2,Influenza,Counties,New Haven,9009,2020,1,Age,>=18 Years,52.4,50.6 to 54.3,<NA>
3,Influenza,Counties,New Haven,9009,2021,1,Age,>=18 Years,50.2,45.4 to 55.8,<NA>
4,Influenza,Counties,New Haven,9009,2018,1,Age,>=18 Years,34.0,32.6 to 35.5,<NA>

In [7]:
df[df['95% CI (%)'].astype(str).str.contains(r'[^0-9.\s%to]', na=False)]

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size
6,Influenza,States/Local Areas,New Jersey,34,2009-10,5,Race and Ethnicity,"American Indian or Alaska Native, Non-Hispanic",57.7,40.2 to 75.2 ‡,48
7,Influenza,States/Local Areas,New Jersey,34,2009-10,4,Race and Ethnicity,"American Indian or Alaska Native, Non-Hispanic",57.7,40.2 to 75.2 ‡,48
11,Influenza,States/Local Areas,New Jersey,34,2009-10,8,Race and Ethnicity,"Asian, Non-Hispanic",NR †,NR †,552
12,Influenza,States/Local Areas,New Jersey,34,2009-10,9,Race and Ethnicity,"American Indian or Alaska Native, Non-Hispanic",NR †,NR †,48
13,Influenza,States/Local Areas,New Jersey,34,2009-10,1,Race and Ethnicity,"American Indian or Alaska Native, Non-Hispanic",57.7,40.2 to 75.2 ‡,48
...,...,...,...,...,...,...,...,...,...,...,...
220712,Influenza,States/Local Areas,Maine,23,2009-10,1,Race and Ethnicity,"Asian, Non-Hispanic",70.3,58.8 to 81.8 ‡,49
220713,Influenza,States/Local Areas,Maine,23,2009-10,10,Race and Ethnicity,"Black, Non-Hispanic",NR †,NR †,50
220714,Influenza,States/Local Areas,Maine,23,2009-10,11,Race and Ethnicity,"Black, Non-Hispanic",30.7,13.8 to 47.6 ‡,50
220715,Influenza,States/Local Areas,Maine,23,2009-10,12,Race and Ethnicity,"Black, Non-Hispanic",30.7,13.8 to 47.6 ‡,50
220716,Influenza,States/Local Areas,Maine,23,2009-10,1,Race and Ethnicity,"Black, Non-Hispanic",38.7,19.0 to 58.4 ‡,50

In [8]:
ci = df['95% CI (%)'].astype(str).str.replace('%', '', regex=False).str.strip()
df[['ci_lower', 'ci_upper']] = ci.str.extract(r'([\d.]+)\s+to\s+([\d.]+)')
df[['ci_lower', 'ci_upper']] = ci.str.split(r'\s+to\s+', expand=True)
df.head()

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size,ci_lower,ci_upper
0,Influenza,Counties,New Haven,9009,2018,1,>=18 Years,Non-Medical Setting,45.5,43.9 to 47.2,<NA>,43.9,47.2
1,Influenza,Counties,New Haven,9009,2021,1,>=18 Years,Non-Medical Setting,53.0,46.0 to 60.9,<NA>,46.0,60.9
2,Influenza,Counties,New Haven,9009,2020,1,Age,>=18 Years,52.4,50.6 to 54.3,<NA>,50.6,54.3
3,Influenza,Counties,New Haven,9009,2021,1,Age,>=18 Years,50.2,45.4 to 55.8,<NA>,45.4,55.8
4,Influenza,Counties,New Haven,9009,2018,1,Age,>=18 Years,34.0,32.6 to 35.5,<NA>,32.6,35.5

In [9]:
# getting the vaccine dimension table from postgres
import psycopg2 as pg
from creds import POSTGRES_USERNAME, POSTGRES_PW
conn = pg.connect(
    dbname='cs689_project',  
    user=POSTGRES_USERNAME,
    password=POSTGRES_PW,
    host='localhost',
    port='5432'
)
cursor = conn.cursor()

In [10]:
cursor.execute("SELECT vaccine_id, cleaned_vaccine, start_date, vaccine_strains FROM vaccine_dim")
mapping_data = cursor.fetchall()

vaccine_mapping = pd.DataFrame(mapping_data, columns=["vaccine_id", "cleaned_vaccine", "start_date", "vaccine_strains"])
vaccine_mapping

,vaccine_id,cleaned_vaccine,start_date,vaccine_strains
0,1,DTaP,2011-09-01,"Diphtheria, Tetanus, and Bordetella pertussis ..."
1,2,Polio,2011-09-01,"Poliovirus Types 1, 2, and 3 (inactivated)"
2,3,Hep B,2011-09-01,Hepatitis B virus (HBV)
3,4,PCV,2011-09-01,Streptococcus pneumoniae — multiple serotypes ...
4,7,Hib,2011-09-01,Haemophilus influenzae type b
5,10,Combined 7 Series,2011-09-01,"Includes: DTaP, IPV, MMR, Hib, Hep B, Varicell..."
6,11,Rotavirus,2011-09-01,"Rotavirus types G1, G2, G3, G4, G9 (Rotarix); ..."
7,9,Influenza,2011-09-01,"A/California/7/2009, A/Victoria/361/2011 (H3N2..."
8,12,Influenza,2012-09-01,"A/California/7/2009, A/Victoria/361/2011 (H3N2..."
9,13,Influenza,2013-09-01,"A/California/7/2009, A/Texas/50/2012 (H3N2), B..."
10,14,Influenza,2014-09-01,"A/California/7/2009, A/Texas/50/2012 (H3N2), B..."
11,15,Influenza,2015-09-01,"A/California/7/2009, A/Switzerland/9715293/201..."
12,16,Influenza,2016-09-01,"A/California/7/2009, A/Hong Kong/4801/2014 (H3..."
13,17,Influenza,2017-09-01,"A/Michigan/45/2015, A/Hong Kong/4801/2014 (H3N..."
14,18,Influenza,2018-09-01,"A/Michigan/45/2015, A/Singapore/INFIMH-16-0019..."
15,19,Influenza,2019-09-01,"A/Brisbane/02/2018, A/Kansas/14/2017 (H3N2), B..."
16,20,Influenza,2020-09-01,"A/Guangdong-Maonan/SWL1536/2019, A/Hong Kong/2..."
17,21,Influenza,2021-09-01,"A/Victoria/2570/2019, A/Cambodia/e0826360/2020..."
18,22,Influenza,2022-09-01,"A/Victoria/2570/2019, A/Darwin/9/2021 (H3N2), ..."
19,23,Influenza,2023-09-01,"A/Victoria/4897/2022, A/Darwin/9/2021 (H3N2), ..."
20,25,HPV,2011-09-01,"HPV Types: 6, 11, 16, 18, 31, 33, 45, 52, 58"
21,26,Tdap,2011-09-01,No strains — protects against the toxin (tetan...
22,27,MenACWY,2011-09-01,"A, C, W, Y (the most common disease-causing st..."
23,28,HepB,2011-09-01,Hepatitis B virus (HBV)
24,6,MMR,2011-09-01,"Measles virus, Mumps virus, Rubella virus"
25,5,Varicella,2011-09-01,Varicella-zoster virus (chickenpox)
26,8,Hep A,2011-09-01,Hepatitis A virus
27,24,Influenza,2024-09-01,"A/Victoria/4897/2022, A/Thailand/8/2022 (H3N2)..."
28,34,Influenza,2009-09-01,"A/Brisbane/59/2007 (H1N1)-like, A/Brisbane/10/..."
29,37,Influenza,2010-09-01,"A/California/7/2009 (H1N1)pdm09-like virus, A/..."
30,35,"Any Influenza Vaccination, Seasonal or H1N1",2009-09-01,A/California/7/2009 (H1N1)pdm09-like
31,36,Influenza A (H1N1) 2009 Monovalent,2009-09-01,"A/Brisbane/59/2007 (H1N1)-like, A/Brisbane/10/..."

In [11]:
vaccine_mapping['start_date'] = pd.to_datetime(vaccine_mapping['start_date'])
vaccine_mapping['year'] = vaccine_mapping['start_date'].dt.year
vaccine_mapping

,vaccine_id,cleaned_vaccine,start_date,vaccine_strains,year
0,1,DTaP,2011-09-01,"Diphtheria, Tetanus, and Bordetella pertussis ...",2011
1,2,Polio,2011-09-01,"Poliovirus Types 1, 2, and 3 (inactivated)",2011
2,3,Hep B,2011-09-01,Hepatitis B virus (HBV),2011
3,4,PCV,2011-09-01,Streptococcus pneumoniae — multiple serotypes ...,2011
4,7,Hib,2011-09-01,Haemophilus influenzae type b,2011
5,10,Combined 7 Series,2011-09-01,"Includes: DTaP, IPV, MMR, Hib, Hep B, Varicell...",2011
6,11,Rotavirus,2011-09-01,"Rotavirus types G1, G2, G3, G4, G9 (Rotarix); ...",2011
7,9,Influenza,2011-09-01,"A/California/7/2009, A/Victoria/361/2011 (H3N2...",2011
8,12,Influenza,2012-09-01,"A/California/7/2009, A/Victoria/361/2011 (H3N2...",2012
9,13,Influenza,2013-09-01,"A/California/7/2009, A/Texas/50/2012 (H3N2), B...",2013
10,14,Influenza,2014-09-01,"A/California/7/2009, A/Texas/50/2012 (H3N2), B...",2014
11,15,Influenza,2015-09-01,"A/California/7/2009, A/Switzerland/9715293/201...",2015
12,16,Influenza,2016-09-01,"A/California/7/2009, A/Hong Kong/4801/2014 (H3...",2016
13,17,Influenza,2017-09-01,"A/Michigan/45/2015, A/Hong Kong/4801/2014 (H3N...",2017
14,18,Influenza,2018-09-01,"A/Michigan/45/2015, A/Singapore/INFIMH-16-0019...",2018
15,19,Influenza,2019-09-01,"A/Brisbane/02/2018, A/Kansas/14/2017 (H3N2), B...",2019
16,20,Influenza,2020-09-01,"A/Guangdong-Maonan/SWL1536/2019, A/Hong Kong/2...",2020
17,21,Influenza,2021-09-01,"A/Victoria/2570/2019, A/Cambodia/e0826360/2020...",2021
18,22,Influenza,2022-09-01,"A/Victoria/2570/2019, A/Darwin/9/2021 (H3N2), ...",2022
19,23,Influenza,2023-09-01,"A/Victoria/4897/2022, A/Darwin/9/2021 (H3N2), ...",2023
20,25,HPV,2011-09-01,"HPV Types: 6, 11, 16, 18, 31, 33, 45, 52, 58",2011
21,26,Tdap,2011-09-01,No strains — protects against the toxin (tetan...,2011
22,27,MenACWY,2011-09-01,"A, C, W, Y (the most common disease-causing st...",2011
23,28,HepB,2011-09-01,Hepatitis B virus (HBV),2011
24,6,MMR,2011-09-01,"Measles virus, Mumps virus, Rubella virus",2011
25,5,Varicella,2011-09-01,Varicella-zoster virus (chickenpox),2011
26,8,Hep A,2011-09-01,Hepatitis A virus,2011
27,24,Influenza,2024-09-01,"A/Victoria/4897/2022, A/Thailand/8/2022 (H3N2)...",2024
28,34,Influenza,2009-09-01,"A/Brisbane/59/2007 (H1N1)-like, A/Brisbane/10/...",2009
29,37,Influenza,2010-09-01,"A/California/7/2009 (H1N1)pdm09-like virus, A/...",2010
30,35,"Any Influenza Vaccination, Seasonal or H1N1",2009-09-01,A/California/7/2009 (H1N1)pdm09-like,2009
31,36,Influenza A (H1N1) 2009 Monovalent,2009-09-01,"A/Brisbane/59/2007 (H1N1)-like, A/Brisbane/10/...",2009

In [12]:
df_counties = df[df['Geography Type'] == 'Counties']
df_counties.head()

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size,ci_lower,ci_upper
0,Influenza,Counties,New Haven,9009,2018,1,>=18 Years,Non-Medical Setting,45.5,43.9 to 47.2,<NA>,43.9,47.2
1,Influenza,Counties,New Haven,9009,2021,1,>=18 Years,Non-Medical Setting,53.0,46.0 to 60.9,<NA>,46.0,60.9
2,Influenza,Counties,New Haven,9009,2020,1,Age,>=18 Years,52.4,50.6 to 54.3,<NA>,50.6,54.3
3,Influenza,Counties,New Haven,9009,2021,1,Age,>=18 Years,50.2,45.4 to 55.8,<NA>,45.4,55.8
4,Influenza,Counties,New Haven,9009,2018,1,Age,>=18 Years,34.0,32.6 to 35.5,<NA>,32.6,35.5

In [13]:
original_length = df_counties.shape[0]
original_length

21818

In [14]:
for _, row in df_counties.iterrows():
    start_year = row['Season/Survey Year'][:4]
    df_counties.loc[_, 'start_cohort_year'] = start_year
    df_counties.loc[_, 'start_cohort_datetime'] = str(start_year) + '-' + str(row['Month'])
df_counties.head()

/var/folders/jq/q12_1s5j0kx30cqlm76w1m740000gn/T/ipykernel_12858/294772658.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_counties.loc[_, 'start_cohort_year'] = start_year
/var/folders/jq/q12_1s5j0kx30cqlm76w1m740000gn/T/ipykernel_12858/294772658.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_counties.loc[_, 'start_cohort_datetime'] = str(start_year) + '-' + str(row['Month'])

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size,ci_lower,ci_upper,start_cohort_year,start_cohort_datetime
0,Influenza,Counties,New Haven,9009,2018,1,>=18 Years,Non-Medical Setting,45.5,43.9 to 47.2,<NA>,43.9,47.2,2018,2018-1
1,Influenza,Counties,New Haven,9009,2021,1,>=18 Years,Non-Medical Setting,53.0,46.0 to 60.9,<NA>,46.0,60.9,2021,2021-1
2,Influenza,Counties,New Haven,9009,2020,1,Age,>=18 Years,52.4,50.6 to 54.3,<NA>,50.6,54.3,2020,2020-1
3,Influenza,Counties,New Haven,9009,2021,1,Age,>=18 Years,50.2,45.4 to 55.8,<NA>,45.4,55.8,2021,2021-1
4,Influenza,Counties,New Haven,9009,2018,1,Age,>=18 Years,34.0,32.6 to 35.5,<NA>,32.6,35.5,2018,2018-1

In [15]:
df_counties['start_cohort_year'] = (pd.to_numeric(df_counties['start_cohort_year'], errors='coerce').astype('Int64'))
df_counties = pd.merge(df_counties, vaccine_mapping, left_on = ['Vaccine', 'start_cohort_year'], right_on=['cleaned_vaccine', 'year'], how='left')
df_counties.head()

/var/folders/jq/q12_1s5j0kx30cqlm76w1m740000gn/T/ipykernel_12858/3523382953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_counties['start_cohort_year'] = (pd.to_numeric(df_counties['start_cohort_year'], errors='coerce').astype('Int64'))

,Vaccine,Geography Type,Geography,FIPS,Season/Survey Year,Month,Dimension Type,Dimension,Estimate (%),95% CI (%),Sample Size,ci_lower,ci_upper,start_cohort_year,start_cohort_datetime,vaccine_id,cleaned_vaccine,start_date,vaccine_strains,year
0,Influenza,Counties,New Haven,9009,2018,1,>=18 Years,Non-Medical Setting,45.5,43.9 to 47.2,<NA>,43.9,47.2,2018,2018-1,18,Influenza,2018-09-01,"A/Michigan/45/2015, A/Singapore/INFIMH-16-0019...",2018
1,Influenza,Counties,New Haven,9009,2021,1,>=18 Years,Non-Medical Setting,53.0,46.0 to 60.9,<NA>,46.0,60.9,2021,2021-1,21,Influenza,2021-09-01,"A/Victoria/2570/2019, A/Cambodia/e0826360/2020...",2021
2,Influenza,Counties,New Haven,9009,2020,1,Age,>=18 Years,52.4,50.6 to 54.3,<NA>,50.6,54.3,2020,2020-1,20,Influenza,2020-09-01,"A/Guangdong-Maonan/SWL1536/2019, A/Hong Kong/2...",2020
3,Influenza,Counties,New Haven,9009,2021,1,Age,>=18 Years,50.2,45.4 to 55.8,<NA>,45.4,55.8,2021,2021-1,21,Influenza,2021-09-01,"A/Victoria/2570/2019, A/Cambodia/e0826360/2020...",2021
4,Influenza,Counties,New Haven,9009,2018,1,Age,>=18 Years,34.0,32.6 to 35.5,<NA>,32.6,35.5,2018,2018-1,18,Influenza,2018-09-01,"A/Michigan/45/2015, A/Singapore/INFIMH-16-0019...",2018

In [16]:
df_counties[df_counties['vaccine_id'].isna()]

Empty DataFrame
Columns: [Vaccine, Geography Type, Geography, FIPS, Season/Survey Year, Month, Dimension Type, Dimension, Estimate (%), 95% CI (%), Sample Size, ci_lower, ci_upper, start_cohort_year, start_cohort_datetime, vaccine_id, cleaned_vaccine, start_date, vaccine_strains, year]
Index: []

In [17]:
df_counties.drop(columns=['Vaccine', 'cleaned_vaccine','vaccine_strains', 'year', 'start_date', 'Season/Survey Year', 'start_cohort_year', 'Month', '95% CI (%)'], inplace=True)
df_counties.head()

,Geography Type,Geography,FIPS,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id
0,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-1,18
1,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-1,21
2,Counties,New Haven,9009,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-1,20
3,Counties,New Haven,9009,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-1,21
4,Counties,New Haven,9009,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-1,18

In [18]:
df_counties['start_cohort_datetime'] = pd.to_datetime(df_counties['start_cohort_datetime']).dt.strftime('%Y-%m-%d')
df_counties.head()

,Geography Type,Geography,FIPS,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id
0,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18
1,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21
2,Counties,New Haven,9009,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20
3,Counties,New Haven,9009,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21
4,Counties,New Haven,9009,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18

In [19]:
# getting state from FIPS
df_counties['FIPS_clean'] = df_counties['FIPS'].astype(str)
for _,row in df_counties.iterrows():
    if len(row['FIPS_clean']) == 4:
        # print(row['FIPS_clean'])
        df_counties.loc[_,'FIPS_clean'] = '0'+ row['FIPS_clean']
df_counties.head()

,Geography Type,Geography,FIPS,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,FIPS_clean
0,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18,09009
1,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21,09009
2,Counties,New Haven,9009,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20,09009
3,Counties,New Haven,9009,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21,09009
4,Counties,New Haven,9009,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18,09009

In [95]:
# getting the state from counties using FIPS
# im not going to call the API 200k+ times, so im going to store the retrieved FIPS information in a dictionary
import requests
from tqdm import tqdm
import time
county_state = {}
chunk_size = 10

# base URL for the Census Bureau 2020 Decennial Census Public Law 94-171 Redistricting Data
url = "https://api.census.gov/data/2020/dec/pl"
## key = key

# Set up the parameters for the API call:
def chunk_dataframe(df, chunk_size):
    for i in range(0, len(df), chunk_size):
        yield df.iloc[i:i+chunk_size]

for chunk in tqdm(chunk_dataframe(df_counties, chunk_size), desc="Processing chunks"):
    for _, row in tqdm(chunk.iterrows(), total=len(chunk), leave=False, desc="Fetching FIPS"):
        fips = row['FIPS_clean']
        if fips in county_state:
            continue
        
        state = fips[:2]
        county = fips[2:]

        params = {
            "get": "NAME",
            "for": f"county:{county}",
            "in": f"state:{state}",
            "key": key

        }

        try:
            response = requests.get(url, params=params, timeout=10)

            if response.status_code == 200:
                data = response.json()
                county_info = data[1]
                county_state[fips] = county_info[0]
            else:
                print(f"Error for {fips}: {response.status_code} - {response.text}")


        except requests.exceptions.Timeout:
            print(f"Timeout for {fips}")
        except Exception as e:
            print(f"Request error for {fips}:", e)
    
    # optional sleep between chunks
    time.sleep(1)

Processing chunks: 0it [00:02, ?it/s]

KeyboardInterrupt:

In [168]:
len(county_state)

3143

In [169]:
county_state

{'09009': 'New Haven County, Connecticut',
 '18035': 'Delaware County, Indiana',
 '19055': 'Delaware County, Iowa',
 '36025': 'Delaware County, New York',
 '39041': 'Delaware County, Ohio',
 '40041': 'Delaware County, Oklahoma',
 '42045': 'Delaware County, Pennsylvania',
 '08029': 'Delta County, Colorado',
 '26041': 'Delta County, Michigan',
 '48119': 'Delta County, Texas',
 '02068': 'Denali Borough, Alaska',
 '29065': 'Dent County, Missouri',
 '48121': 'Denton County, Texas',
 '08031': 'Denver County, Colorado',
 '19057': 'Des Moines County, Iowa',
 '41017': 'Deschutes County, Oregon',
 '05041': 'Desha County, Arkansas',
 '12027': 'DeSoto County, Florida',
 '28033': 'DeSoto County, Mississippi',
 '31049': 'Deuel County, Nebraska',
 '46039': 'Deuel County, South Dakota',
 '40043': 'Dewey County, Oklahoma',
 '46041': 'Dewey County, South Dakota',
 '48123': 'DeWitt County, Texas',
 '48125': 'Dickens County, Texas',
 '51051': 'Dickenson County, Virginia',
 '38021': 'Dickey County, North Dakota',
 '19059': 'Dickinson County, Iowa',
 '20041': 'Dickinson County, Kansas',
 '26043': 'Dickinson County, Michigan',
 '47043': 'Dickson County, Tennessee',
 '02070': 'Dillingham Census Area, Alaska',
 '45033': 'Dillon County, South Carolina',
 '48127': 'Dimmit County, Texas',
 '51053': 'Dinwiddie County, Virginia',
 '40109': 'Oklahoma County, Oklahoma',
 '40111': 'Okmulgee County, Oklahoma',
 '28105': 'Oktibbeha County, Mississippi',
 '21185': 'Oldham County, Kentucky',
 '48359': 'Oldham County, Texas',
 '38065': 'Oliver County, North Dakota',
 '27109': 'Olmsted County, Minnesota',
 '16071': 'Oneida County, Idaho',
 '36065': 'Oneida County, New York',
 '55085': 'Oneida County, Wisconsin',
 '36067': 'Onondaga County, New York',
 '37133': 'Onslow County, North Carolina',
 '36069': 'Ontario County, New York',
 '26131': 'Ontonagon County, Michigan',
 '06059': 'Orange County, California',
 '12095': 'Orange County, Florida',
 '18117': 'Orange County, Indiana',
 '36071': 'Orange County, New York',
 '37135': 'Orange County, North Carolina',
 '48361': 'Orange County, Texas',
 '50017': 'Orange County, Vermont',
 '51137': 'Orange County, Virginia',
 '45075': 'Orangeburg County, South Carolina',
 '29149': 'Oregon County, Missouri',
 '42063': 'Indiana County, Pennsylvania',
 '26065': 'Ingham County, Michigan',
 '06027': 'Inyo County, California',
 '26067': 'Ionia County, Michigan',
 '26069': 'Iosco County, Michigan',
 '13205': 'Mitchell County, Georgia',
 '19131': 'Mitchell County, Iowa',
 '20123': 'Mitchell County, Kansas',
 '37121': 'Mitchell County, North Carolina',
 '48335': 'Mitchell County, Texas',
 '01097': 'Mobile County, Alabama',
 '06049': 'Modoc County, California',
 '08081': 'Moffat County, Colorado',
 '04015': 'Mohave County, Arizona',
 '29135': 'Moniteau County, Missouri',
 '34025': 'Monmouth County, New Jersey',
 '06051': 'Mono County, California',
 '19133': 'Monona County, Iowa',
 '54061': 'Monongalia County, West Virginia',
 '01099': 'Monroe County, Alabama',
 '05095': 'Monroe County, Arkansas',
 '12087': 'Monroe County, Florida',
 '13207': 'Monroe County, Georgia',
 '17133': 'Monroe County, Illinois',
 '18105': 'Monroe County, Indiana',
 '19135': 'Monroe County, Iowa',
 '21171': 'Monroe County, Kentucky',
 '26115': 'Monroe County, Michigan',
 '28095': 'Monroe County, Mississippi',
 '29137': 'Monroe County, Missouri',
 '36055': 'Monroe County, New York',
 '39111': 'Monroe County, Ohio',
 '26113': 'Missaukee County, Michigan',
 '05093': 'Mississippi County, Arkansas',
 '36073': 'Orleans County, New York',
 '50019': 'Orleans County, Vermont',
 '22071': 'Orleans Parish, Louisiana',
 '20139': 'Osage County, Kansas',
 '29151': 'Osage County, Missouri',
 '40113': 'Osage County, Oklahoma',
 '20141': 'Osborne County, Kansas',
 '12097': 'Osceola County, Florida',
 '19143': 'Osceola County, Iowa',
 '26133': 'Osceola County, Michigan',
 '26135': 'Oscoda County, Michigan',
 '36075': 'Oswego County, New York',
 '08089': 'Otero County, Colorado',
 '35035': 'Otero County, New Mexico',
 '31131': 'Otoe County, Nebraska',
 '26137': 'Otsego County, Michigan',
 '36077': 'Otsego County, New York',
 '20143': 'Ottawa County, Kansas',
 '26139': 'Ottawa County, Michigan',
 '39123': 'Ottawa County, Ohio',
 '40115': 'Ottawa County, Oklahoma',
 '27111': 'Otter Tail County, Minnesota',
 '05103': 'Ouachita County, Arkansas',
 '22073': 'Ouachita Parish, Louisiana',
 '08091': 'Ouray County, Colorado',
 '55087': 'Outagamie County, Wisconsin',
 '47133': 'Overton County, Tennessee',
 '18119': 'Owen County, Indiana',
 '21187': 'Owen County, Kentucky',
 '21189': 'Owsley County, Kentucky',
 '16073': 'Owyhee County, Idaho',
 '23017': 'Oxford County, Maine',
 '29153': 'Ozark County, Missouri',
 '17125': 'Mason County, Illinois',
 '21161': 'Mason County, Kentucky',
 '26105': 'Mason County, Michigan',
 '48319': 'Mason County, Texas',
 '53045': 'Mason County, Washington',
 '54053': 'Mason County, West Virginia',
 '17127': 'Massac County, Illinois',
 '40093': 'Major County, Oklahoma',
 '41045': 'Malheur County, Oregon',
 '51683': 'Manassas city, Virginia',
 '51685': 'Manassas Park city, Virginia',
 '12081': 'Manatee County, Florida',
 '26101': 'Manistee County, Michigan',
 '55071': 'Manitowoc County, Wisconsin',
 '55073': 'Marathon County, Wisconsin',
 '01091': 'Marengo County, Alabama',
 '04013': 'Maricopa County, Arizona',
 '45001': 'Abbeville County, South Carolina',
 '22001': 'Acadia Parish, Louisiana',
 '51001': 'Accomack County, Virginia',
 '16001': 'Ada County, Idaho',
 '19001': 'Adair County, Iowa',
 '21001': 'Adair County, Kentucky',
 '29001': 'Adair County, Missouri',
 '40001': 'Adair County, Oklahoma',
 '08001': 'Adams County, Colorado',
 '16003': 'Adams County, Idaho',
 '17001': 'Adams County, Illinois',
 '18001': 'Adams County, Indiana',
 '19003': 'Adams County, Iowa',
 '28001': 'Adams County, Mississippi',
 '31001': 'Adams County, Nebraska',
 '38001': 'Adams County, North Dakota',
 '39001': 'Adams County, Ohio',
 '42001': 'Adams County, Pennsylvania',
 '53001': 'Adams County, Washington',
 '55001': 'Adams County, Wisconsin',
 '50001': 'Addison County, Vermont',
 '45003': 'Aiken County, South Carolina',
 '27001': 'Aitkin County, Minnesota',
 '22107': 'Tensas Parish, Louisiana',
 '22109': 'Terrebonne Parish, Louisiana',
 '13273': 'Terrell County, Georgia',
 '48443': 'Terrell County, Texas',
 '48445': 'Terry County, Texas',
 '16081': 'Teton County, Idaho',
 '30099': 'Teton County, Montana',
 '56039': 'Teton County, Wyoming',
 '29215': 'Texas County, Missouri',
 '40139': 'Texas County, Oklahoma',
 '05119': 'Pulaski County, Arkansas',
 '13235': 'Pulaski County, Georgia',
 '17153': 'Pulaski County, Illinois',
 '18131': 'Pulaski County, Indiana',
 '21199': 'Pulaski County, Kentucky',
 '29169': 'Pulaski County, Missouri',
 '51155': 'Pulaski County, Virginia',
 '40127': 'Pushmataha County, Oklahoma',
 '12107': 'Putnam County, Florida',
 '13237': 'Putnam County, Georgia',
 '17155': 'Putnam County, Illinois',
 '18133': 'Putnam County, Indiana',
 '29171': 'Putnam County, Missouri',
 '36079': 'Putnam County, New York',
 '39137': 'Putnam County, Ohio',
 '47141': 'Putnam County, Tennessee',
 '54079': 'Putnam County, West Virginia',
 '35037': 'Quay County, New Mexico',
 '24035': "Queen Anne's County, Maryland",
 '36081': 'Queens County, New York',
 '13239': 'Quitman County, Georgia',
 '28119': 'Quitman County, Mississippi',
 '13241': 'Rabun County, Georgia',
 '55101': 'Racine County, Wisconsin',
 '51750': 'Radford city, Virginia',
 '48379': 'Rains County, Texas',
 '54081': 'Raleigh County, West Virginia',
 '29173': 'Ralls County, Missouri',
 '27123': 'Ramsey County, Minnesota',
 '38071': 'Ramsey County, North Dakota',
 '48381': 'Randall County, Texas',
 '01111': 'Randolph County, Alabama',
 '05121': 'Randolph County, Arkansas',
 '13243': 'Randolph County, Georgia',
 '17157': 'Randolph County, Illinois',
 '18135': 'Randolph County, Indiana',
 '29175': 'Randolph County, Missouri',
 '37151': 'Randolph County, North Carolina',
 '54083': 'Randolph County, West Virginia',
 '28121': 'Rankin County, Mississippi',
 '38073': 'Ransom County, North Dakota',
 '22079': 'Rapides Parish, Louisiana',
 '51157': 'Rappahannock County, Virginia',
 '30081': 'Ravalli County, Montana',
 '20153': 'Rawlins County, Kansas',
 '29177': 'Ray County, Missouri',
 '48383': 'Reagan County, Texas',
 '48385': 'Real County, Texas',
 '27125': 'Red Lake County, Minnesota',
 '48387': 'Red River County, Texas',
 '22081': 'Red River Parish, Louisiana',
 '31145': 'Red Willow County, Nebraska',
 '27127': 'Redwood County, Minnesota',
 '48389': 'Reeves County, Texas',
 '48391': 'Refugio County, Texas',
 '20159': 'Rice County, Kansas',
 '27131': 'Rice County, Minnesota',
 '49033': 'Rich County, Utah',
 '31147': 'Richardson County, Nebraska',
 '17159': 'Richland County, Illinois',
 '30083': 'Richland County, Montana',
 '38077': 'Richland County, North Dakota',
 '39139': 'Richland County, Ohio',
 '45079': 'Richland County, South Carolina',
 '55103': 'Richland County, Wisconsin',
 '22083': 'Richland Parish, Louisiana',
 '13245': 'Richmond County, Georgia',
 '36085': 'Richmond County, New York',
 '37153': 'Richmond County, North Carolina',
 '51159': 'Richmond County, Virginia',
 '51760': 'Richmond city, Virginia',
 '20161': 'Riley County, Kansas',
 '19159': 'Ringgold County, Iowa',
 '35039': 'Rio Arriba County, New Mexico',
 '08103': 'Rio Blanco County, Colorado',
 '08105': 'Rio Grande County, Colorado',
 '18137': 'Ripley County, Indiana',
 '29181': 'Ripley County, Missouri',
 '54085': 'Ritchie County, West Virginia',
 '06065': 'Riverside County, California',
 '47145': 'Roane County, Tennessee',
 '54087': 'Roane County, West Virginia',
 '51161': 'Roanoke County, Virginia',
 '51770': 'Roanoke city, Virginia',
 '46109': 'Roberts County, South Dakota',
 '48393': 'Roberts County, Texas',
 '21201': 'Robertson County, Kentucky',
 '47147': 'Robertson County, Tennessee',
 '48395': 'Robertson County, Texas',
 '37155': 'Robeson County, North Carolina',
 '27133': 'Rock County, Minnesota',
 '31149': 'Rock County, Nebraska',
 '55105': 'Rock County, Wisconsin',
 '17161': 'Rock Island County, Illinois',
 '51163': 'Rockbridge County, Virginia',
 '21203': 'Rockcastle County, Kentucky',
 '13247': 'Rockdale County, Georgia',
 '33015': 'Rockingham County, New Hampshire',
 '37157': 'Rockingham County, North Carolina',
 '51165': 'Rockingham County, Virginia',
 '36087': 'Rockland County, New York',
 '48397': 'Rockwall County, Texas',
 '40129': 'Roger Mills County, Oklahoma',
 '40131': 'Rogers County, Oklahoma',
 '38079': 'Rolette County, North Dakota',
 '20163': 'Rooks County, Kansas',
 '30085': 'Roosevelt County, Montana',
 '35041': 'Roosevelt County, New Mexico',
 '26143': 'Roscommon County, Michigan',
 '27135': 'Roseau County, Minnesota',
 '30087': 'Rosebud County, Montana',
 '39141': 'Ross County, Ohio',
 '08107': 'Routt County, Colorado',
 '21205': 'Rowan County, Kentucky',
 '37159': 'Rowan County, North Carolina',
 '48399': 'Runnels County, Texas',
 '18139': 'Rush County, Indiana',
 '20165': 'Rush County, Kansas',
 '48401': 'Rusk County, Texas',
 '55107': 'Rusk County, Wisconsin',
 '01113': 'Russell County, Alabama',
 '20167': 'Russell County, Kansas',
 '21207': 'Russell County, Kentucky',
 '51167': 'Russell County, Virginia',
 '37161': 'Rutherford County, North Carolina',
 '47149': 'Rutherford County, Tennessee',
 '50021': 'Rutland County, Vermont',
 '48403': 'Sabine County, Texas',
 '22085': 'Sabine Parish, Louisiana',
 '19161': 'Sac County, Iowa',
 '06067': 'Sacramento County, California',
 '23023': 'Sagadahoc County, Maine',
 '26145': 'Saginaw County, Michigan',
 '08109': 'Saguache County, Colorado',
 '34033': 'Salem County, New Jersey',
 '51775': 'Salem city, Virginia',
 '05125': 'Saline County, Arkansas',
 '17165': 'Saline County, Illinois',
 '20169': 'Saline County, Kansas',
 '29195': 'Saline County, Missouri',
 '31151': 'Saline County, Nebraska',
 '49035': 'Salt Lake County, Utah',
 '45081': 'Saluda County, South Carolina',
 '37163': 'Sampson County, North Carolina',
 '48405': 'San Augustine County, Texas',
 '06069': 'San Benito County, California',
 '06071': 'San Bernardino County, California',
 '06073': 'San Diego County, California',
 '06075': 'San Francisco County, California',
 '48407': 'San Jacinto County, Texas',
 '06077': 'San Joaquin County, California',
 '08111': 'San Juan County, Colorado',
 '35045': 'San Juan County, New Mexico',
 '49037': 'San Juan County, Utah',
 '53055': 'San Juan County, Washington',
 '06079': 'San Luis Obispo County, California',
 '06081': 'San Mateo County, California',
 '08113': 'San Miguel County, Colorado',
 '35047': 'San Miguel County, New Mexico',
 '48409': 'San Patricio County, Texas',
 '48411': 'San Saba County, Texas',
 '46111': 'Sanborn County, South Dakota',
 '30089': 'Sanders County, Montana',
 '35043': 'Sandoval County, New Mexico',
 '39143': 'Sandusky County, Ohio',
 '17167': 'Sangamon County, Illinois',
 '26151': 'Sanilac County, Michigan',
 '49039': 'Sanpete County, Utah',
 '06083': 'Santa Barbara County, California',
 '06085': 'Santa Clara County, California',
 '04023': 'Santa Cruz County, Arizona',
 '06087': 'Santa Cruz County, California',
 '35049': 'Santa Fe County, New Mexico',
 '12113': 'Santa Rosa County, Florida',
 '12115': 'Sarasota County, Florida',
 '36091': 'Saratoga County, New York',
 '38081': 'Sargent County, North Dakota',
 '31153': 'Sarpy County, Nebraska',
 '55111': 'Sauk County, Wisconsin',
 '31155': 'Saunders County, Nebraska',
 '55113': 'Sawyer County, Wisconsin',
 '36093': 'Schenectady County, New York',
 '48413': 'Schleicher County, Texas',
 '13249': 'Schley County, Georgia',
 '36095': 'Schoharie County, New York',
 '26153': 'Schoolcraft County, Michigan',
 '17169': 'Schuyler County, Illinois',
 '29197': 'Schuyler County, Missouri',
 '36097': 'Schuyler County, New York',
 '42107': 'Schuylkill County, Pennsylvania',
 '39145': 'Scioto County, Ohio',
 '29199': 'Scotland County, Missouri',
 '37165': 'Scotland County, North Carolina',
 '05127': 'Scott County, Arkansas',
 '17171': 'Scott County, Illinois',
 '18143': 'Scott County, Indiana',
 '19163': 'Scott County, Iowa',
 '20171': 'Scott County, Kansas',
 '21209': 'Scott County, Kentucky',
 '27139': 'Scott County, Minnesota',
 '28123': 'Scott County, Mississippi',
 '29201': 'Scott County, Missouri',
 '47151': 'Scott County, Tennessee',
 '51169': 'Scott County, Virginia',
 '31157': 'Scotts Bluff County, Nebraska',
 '13251': 'Screven County, Georgia',
 '48415': 'Scurry County, Texas',
 '05129': 'Searcy County, Arkansas',
 '05131': 'Sebastian County, Arkansas',
 '08115': 'Sedgwick County, Colorado',
 '20173': 'Sedgwick County, Kansas',
 '12117': 'Seminole County, Florida',
 '13253': 'Seminole County, Georgia',
 '40133': 'Seminole County, Oklahoma',
 '36099': 'Seneca County, New York',
 '39147': 'Seneca County, Ohio',
 '47153': 'Sequatchie County, Tennessee',
 '40135': 'Sequoyah County, Oklahoma',
 '05133': 'Sevier County, Arkansas',
 '47155': 'Sevier County, Tennessee',
 '49041': 'Sevier County, Utah',
 '20175': 'Seward County, Kansas',
 '31159': 'Seward County, Nebraska',
 '48417': 'Shackelford County, Texas',
 '29203': 'Shannon County, Missouri',
 '28125': 'Sharkey County, Mississippi',
 '05135': 'Sharp County, Arkansas',
 '06089': 'Shasta County, California',
 '55115': 'Shawano County, Wisconsin',
 '20177': 'Shawnee County, Kansas',
 '55117': 'Sheboygan County, Wisconsin',
 '01117': 'Shelby County, Alabama',
 '17173': 'Shelby County, Illinois',
 '18145': 'Shelby County, Indiana',
 '19165': 'Shelby County, Iowa',
 '21211': 'Shelby County, Kentucky',
 '29205': 'Shelby County, Missouri',
 '39149': 'Shelby County, Ohio',
 '47157': 'Shelby County, Tennessee',
 '48419': 'Shelby County, Texas',
 '51171': 'Shenandoah County, Virginia',
 '27141': 'Sherburne County, Minnesota',
 '20179': 'Sheridan County, Kansas',
 '30091': 'Sheridan County, Montana',
 '31161': 'Sheridan County, Nebraska',
 '38083': 'Sheridan County, North Dakota',
 '56033': 'Sheridan County, Wyoming',
 '20181': 'Sherman County, Kansas',
 '31163': 'Sherman County, Nebraska',
 '41055': 'Sherman County, Oregon',
 '48421': 'Sherman County, Texas',
 '26155': 'Shiawassee County, Michigan',
 '16079': 'Shoshone County, Idaho',
 '27143': 'Sibley County, Minnesota',
 '06091': 'Sierra County, California',
 '35051': 'Sierra County, New Mexico',
 '30093': 'Silver Bow County, Montana',
 '21213': 'Simpson County, Kentucky',
 '28127': 'Simpson County, Mississippi',
 '19167': 'Sioux County, Iowa',
 '31165': 'Sioux County, Nebraska',
 '38085': 'Sioux County, North Dakota',
 '06093': 'Siskiyou County, California',
 '02220': 'Sitka City and Borough, Alaska',
 '53057': 'Skagit County, Washington',
 '02230': 'Skagway Municipality, Alaska',
 '53059': 'Skamania County, Washington',
 '38087': 'Slope County, North Dakota',
 '20183': 'Smith County, Kansas',
 '28129': 'Smith County, Mississippi',
 '47159': 'Smith County, Tennessee',
 '48423': 'Smith County, Texas',
 '51173': 'Smyth County, Virginia',
 '53061': 'Snohomish County, Washington',
 '42109': 'Snyder County, Pennsylvania',
 '35053': 'Socorro County, New Mexico',
 '06095': 'Solano County, California',
 '23025': 'Somerset County, Maine',
 '24039': 'Somerset County, Maryland',
 '34035': 'Somerset County, New Jersey',
 '42111': 'Somerset County, Pennsylvania',
 '48425': 'Somervell County, Texas',
 '06097': 'Sonoma County, California',
 '05001': 'Arkansas County, Arkansas',
 '51013': 'Arlington County, Virginia',
 '42005': 'Armstrong County, Pennsylvania',
 '48011': 'Armstrong County, Texas',
 '23003': 'Aroostook County, Maine',
 '31005': 'Arthur County, Nebraska',
 '22005': 'Ascension Parish, Louisiana',
 '37009': 'Ashe County, North Carolina',
 '39005': 'Ashland County, Ohio',
 '55003': 'Ashland County, Wisconsin',
 '05003': 'Ashley County, Arkansas',
 '39007': 'Ashtabula County, Ohio',
 '53003': 'Asotin County, Washington',
 '22007': 'Assumption Parish, Louisiana',
 '48013': 'Atascosa County, Texas',
 '20005': 'Atchison County, Kansas',
 '29005': 'Atchison County, Missouri',
 '39009': 'Athens County, Ohio',
 '13003': 'Atkinson County, Georgia',
 '34001': 'Atlantic County, New Jersey',
 '40005': 'Atoka County, Oklahoma',
 '28007': 'Attala County, Mississippi',
 '29007': 'Audrain County, Missouri',
 '19009': 'Audubon County, Iowa',
 '39011': 'Auglaize County, Ohio',
 '51015': 'Augusta County, Virginia',
 '46003': 'Aurora County, South Dakota',
 '48015': 'Austin County, Texas',
 '01001': 'Autauga County, Alabama',
 '37011': 'Avery County, North Carolina',
 '22009': 'Avoyelles Parish, Louisiana',
 '08009': 'Baca County, Colorado',
 '13005': 'Bacon County, Georgia',
 '48017': 'Bailey County, Texas',
 '12003': 'Baker County, Florida',
 '13007': 'Baker County, Georgia',
 '41001': 'Baker County, Oregon',
 '01003': 'Baldwin County, Alabama',
 '13009': 'Baldwin County, Georgia',
 '21007': 'Ballard County, Kentucky',
 '24005': 'Baltimore County, Maryland',
 '24510': 'Baltimore city, Maryland',
 '45009': 'Bamberg County, South Carolina',
 '48019': 'Bandera County, Texas',
 '13011': 'Banks County, Georgia',
 '31007': 'Banner County, Nebraska',
 '16005': 'Bannock County, Idaho',
 '26013': 'Baraga County, Michigan',
 '20007': 'Barber County, Kansas',
 '01005': 'Barbour County, Alabama',
 '54001': 'Barbour County, West Virginia',
 '38003': 'Barnes County, North Dakota',
 '25001': 'Barnstable County, Massachusetts',
 '45011': 'Barnwell County, South Carolina',
 '21009': 'Barren County, Kentucky',
 '55005': 'Barron County, Wisconsin',
 '13013': 'Barrow County, Georgia',
 '26015': 'Barry County, Michigan',
 '29009': 'Barry County, Missouri',
 '18005': 'Bartholomew County, Indiana',
 '20009': 'Barton County, Kansas',
 '29011': 'Barton County, Missouri',
 '13015': 'Bartow County, Georgia',
 '48021': 'Bastrop County, Texas',
 '29013': 'Bates County, Missouri',
 '21011': 'Bath County, Kentucky',
 '51017': 'Bath County, Virginia',

## DANGER ZONE! 
### Running the script below without running the script above will overwrite the json file!

In [170]:
with open('fips_mapping.json', 'w') as f:
    json.dump(county_state, f)

In [20]:
import json
with open('fips_mapping.json', 'r') as file:
    data = json.load(file)
data

{'09009': 'New Haven County, Connecticut',
 '18035': 'Delaware County, Indiana',
 '19055': 'Delaware County, Iowa',
 '36025': 'Delaware County, New York',
 '39041': 'Delaware County, Ohio',
 '40041': 'Delaware County, Oklahoma',
 '42045': 'Delaware County, Pennsylvania',
 '08029': 'Delta County, Colorado',
 '26041': 'Delta County, Michigan',
 '48119': 'Delta County, Texas',
 '02068': 'Denali Borough, Alaska',
 '29065': 'Dent County, Missouri',
 '48121': 'Denton County, Texas',
 '08031': 'Denver County, Colorado',
 '19057': 'Des Moines County, Iowa',
 '41017': 'Deschutes County, Oregon',
 '05041': 'Desha County, Arkansas',
 '12027': 'DeSoto County, Florida',
 '28033': 'DeSoto County, Mississippi',
 '31049': 'Deuel County, Nebraska',
 '46039': 'Deuel County, South Dakota',
 '40043': 'Dewey County, Oklahoma',
 '46041': 'Dewey County, South Dakota',
 '48123': 'DeWitt County, Texas',
 '48125': 'Dickens County, Texas',
 '51051': 'Dickenson County, Virginia',
 '38021': 'Dickey County, North Dakota',
 '19059': 'Dickinson County, Iowa',
 '20041': 'Dickinson County, Kansas',
 '26043': 'Dickinson County, Michigan',
 '47043': 'Dickson County, Tennessee',
 '02070': 'Dillingham Census Area, Alaska',
 '45033': 'Dillon County, South Carolina',
 '48127': 'Dimmit County, Texas',
 '51053': 'Dinwiddie County, Virginia',
 '40109': 'Oklahoma County, Oklahoma',
 '40111': 'Okmulgee County, Oklahoma',
 '28105': 'Oktibbeha County, Mississippi',
 '21185': 'Oldham County, Kentucky',
 '48359': 'Oldham County, Texas',
 '38065': 'Oliver County, North Dakota',
 '27109': 'Olmsted County, Minnesota',
 '16071': 'Oneida County, Idaho',
 '36065': 'Oneida County, New York',
 '55085': 'Oneida County, Wisconsin',
 '36067': 'Onondaga County, New York',
 '37133': 'Onslow County, North Carolina',
 '36069': 'Ontario County, New York',
 '26131': 'Ontonagon County, Michigan',
 '06059': 'Orange County, California',
 '12095': 'Orange County, Florida',
 '18117': 'Orange County, Indiana',
 '36071': 'Orange County, New York',
 '37135': 'Orange County, North Carolina',
 '48361': 'Orange County, Texas',
 '50017': 'Orange County, Vermont',
 '51137': 'Orange County, Virginia',
 '45075': 'Orangeburg County, South Carolina',
 '29149': 'Oregon County, Missouri',
 '42063': 'Indiana County, Pennsylvania',
 '26065': 'Ingham County, Michigan',
 '06027': 'Inyo County, California',
 '26067': 'Ionia County, Michigan',
 '26069': 'Iosco County, Michigan',
 '13205': 'Mitchell County, Georgia',
 '19131': 'Mitchell County, Iowa',
 '20123': 'Mitchell County, Kansas',
 '37121': 'Mitchell County, North Carolina',
 '48335': 'Mitchell County, Texas',
 '01097': 'Mobile County, Alabama',
 '06049': 'Modoc County, California',
 '08081': 'Moffat County, Colorado',
 '04015': 'Mohave County, Arizona',
 '29135': 'Moniteau County, Missouri',
 '34025': 'Monmouth County, New Jersey',
 '06051': 'Mono County, California',
 '19133': 'Monona County, Iowa',
 '54061': 'Monongalia County, West Virginia',
 '01099': 'Monroe County, Alabama',
 '05095': 'Monroe County, Arkansas',
 '12087': 'Monroe County, Florida',
 '13207': 'Monroe County, Georgia',
 '17133': 'Monroe County, Illinois',
 '18105': 'Monroe County, Indiana',
 '19135': 'Monroe County, Iowa',
 '21171': 'Monroe County, Kentucky',
 '26115': 'Monroe County, Michigan',
 '28095': 'Monroe County, Mississippi',
 '29137': 'Monroe County, Missouri',
 '36055': 'Monroe County, New York',
 '39111': 'Monroe County, Ohio',
 '26113': 'Missaukee County, Michigan',
 '05093': 'Mississippi County, Arkansas',
 '36073': 'Orleans County, New York',
 '50019': 'Orleans County, Vermont',
 '22071': 'Orleans Parish, Louisiana',
 '20139': 'Osage County, Kansas',
 '29151': 'Osage County, Missouri',
 '40113': 'Osage County, Oklahoma',
 '20141': 'Osborne County, Kansas',
 '12097': 'Osceola County, Florida',
 '19143': 'Osceola County, Iowa',
 '26133': 'Osceola County, Michigan',
 '26135': 'Oscoda County, Michigan',
 '36075': 'Oswego County, New York',
 '08089': 'Otero County, Colorado',
 '35035': 'Otero County, New Mexico',
 '31131': 'Otoe County, Nebraska',
 '26137': 'Otsego County, Michigan',
 '36077': 'Otsego County, New York',
 '20143': 'Ottawa County, Kansas',
 '26139': 'Ottawa County, Michigan',
 '39123': 'Ottawa County, Ohio',
 '40115': 'Ottawa County, Oklahoma',
 '27111': 'Otter Tail County, Minnesota',
 '05103': 'Ouachita County, Arkansas',
 '22073': 'Ouachita Parish, Louisiana',
 '08091': 'Ouray County, Colorado',
 '55087': 'Outagamie County, Wisconsin',
 '47133': 'Overton County, Tennessee',
 '18119': 'Owen County, Indiana',
 '21187': 'Owen County, Kentucky',
 '21189': 'Owsley County, Kentucky',
 '16073': 'Owyhee County, Idaho',
 '23017': 'Oxford County, Maine',
 '29153': 'Ozark County, Missouri',
 '17125': 'Mason County, Illinois',
 '21161': 'Mason County, Kentucky',
 '26105': 'Mason County, Michigan',
 '48319': 'Mason County, Texas',
 '53045': 'Mason County, Washington',
 '54053': 'Mason County, West Virginia',
 '17127': 'Massac County, Illinois',
 '40093': 'Major County, Oklahoma',
 '41045': 'Malheur County, Oregon',
 '51683': 'Manassas city, Virginia',
 '51685': 'Manassas Park city, Virginia',
 '12081': 'Manatee County, Florida',
 '26101': 'Manistee County, Michigan',
 '55071': 'Manitowoc County, Wisconsin',
 '55073': 'Marathon County, Wisconsin',
 '01091': 'Marengo County, Alabama',
 '04013': 'Maricopa County, Arizona',
 '45001': 'Abbeville County, South Carolina',
 '22001': 'Acadia Parish, Louisiana',
 '51001': 'Accomack County, Virginia',
 '16001': 'Ada County, Idaho',
 '19001': 'Adair County, Iowa',
 '21001': 'Adair County, Kentucky',
 '29001': 'Adair County, Missouri',
 '40001': 'Adair County, Oklahoma',
 '08001': 'Adams County, Colorado',
 '16003': 'Adams County, Idaho',
 '17001': 'Adams County, Illinois',
 '18001': 'Adams County, Indiana',
 '19003': 'Adams County, Iowa',
 '28001': 'Adams County, Mississippi',
 '31001': 'Adams County, Nebraska',
 '38001': 'Adams County, North Dakota',
 '39001': 'Adams County, Ohio',
 '42001': 'Adams County, Pennsylvania',
 '53001': 'Adams County, Washington',
 '55001': 'Adams County, Wisconsin',
 '50001': 'Addison County, Vermont',
 '45003': 'Aiken County, South Carolina',
 '27001': 'Aitkin County, Minnesota',
 '22107': 'Tensas Parish, Louisiana',
 '22109': 'Terrebonne Parish, Louisiana',
 '13273': 'Terrell County, Georgia',
 '48443': 'Terrell County, Texas',
 '48445': 'Terry County, Texas',
 '16081': 'Teton County, Idaho',
 '30099': 'Teton County, Montana',
 '56039': 'Teton County, Wyoming',
 '29215': 'Texas County, Missouri',
 '40139': 'Texas County, Oklahoma',
 '05119': 'Pulaski County, Arkansas',
 '13235': 'Pulaski County, Georgia',
 '17153': 'Pulaski County, Illinois',
 '18131': 'Pulaski County, Indiana',
 '21199': 'Pulaski County, Kentucky',
 '29169': 'Pulaski County, Missouri',
 '51155': 'Pulaski County, Virginia',
 '40127': 'Pushmataha County, Oklahoma',
 '12107': 'Putnam County, Florida',
 '13237': 'Putnam County, Georgia',
 '17155': 'Putnam County, Illinois',
 '18133': 'Putnam County, Indiana',
 '29171': 'Putnam County, Missouri',
 '36079': 'Putnam County, New York',
 '39137': 'Putnam County, Ohio',
 '47141': 'Putnam County, Tennessee',
 '54079': 'Putnam County, West Virginia',
 '35037': 'Quay County, New Mexico',
 '24035': "Queen Anne's County, Maryland",
 '36081': 'Queens County, New York',
 '13239': 'Quitman County, Georgia',
 '28119': 'Quitman County, Mississippi',
 '13241': 'Rabun County, Georgia',
 '55101': 'Racine County, Wisconsin',
 '51750': 'Radford city, Virginia',
 '48379': 'Rains County, Texas',
 '54081': 'Raleigh County, West Virginia',
 '29173': 'Ralls County, Missouri',
 '27123': 'Ramsey County, Minnesota',
 '38071': 'Ramsey County, North Dakota',
 '48381': 'Randall County, Texas',
 '01111': 'Randolph County, Alabama',
 '05121': 'Randolph County, Arkansas',
 '13243': 'Randolph County, Georgia',
 '17157': 'Randolph County, Illinois',
 '18135': 'Randolph County, Indiana',
 '29175': 'Randolph County, Missouri',
 '37151': 'Randolph County, North Carolina',
 '54083': 'Randolph County, West Virginia',
 '28121': 'Rankin County, Mississippi',
 '38073': 'Ransom County, North Dakota',
 '22079': 'Rapides Parish, Louisiana',
 '51157': 'Rappahannock County, Virginia',
 '30081': 'Ravalli County, Montana',
 '20153': 'Rawlins County, Kansas',
 '29177': 'Ray County, Missouri',
 '48383': 'Reagan County, Texas',
 '48385': 'Real County, Texas',
 '27125': 'Red Lake County, Minnesota',
 '48387': 'Red River County, Texas',
 '22081': 'Red River Parish, Louisiana',
 '31145': 'Red Willow County, Nebraska',
 '27127': 'Redwood County, Minnesota',
 '48389': 'Reeves County, Texas',
 '48391': 'Refugio County, Texas',
 '20159': 'Rice County, Kansas',
 '27131': 'Rice County, Minnesota',
 '49033': 'Rich County, Utah',
 '31147': 'Richardson County, Nebraska',
 '17159': 'Richland County, Illinois',
 '30083': 'Richland County, Montana',
 '38077': 'Richland County, North Dakota',
 '39139': 'Richland County, Ohio',
 '45079': 'Richland County, South Carolina',
 '55103': 'Richland County, Wisconsin',
 '22083': 'Richland Parish, Louisiana',
 '13245': 'Richmond County, Georgia',
 '36085': 'Richmond County, New York',
 '37153': 'Richmond County, North Carolina',
 '51159': 'Richmond County, Virginia',
 '51760': 'Richmond city, Virginia',
 '20161': 'Riley County, Kansas',
 '19159': 'Ringgold County, Iowa',
 '35039': 'Rio Arriba County, New Mexico',
 '08103': 'Rio Blanco County, Colorado',
 '08105': 'Rio Grande County, Colorado',
 '18137': 'Ripley County, Indiana',
 '29181': 'Ripley County, Missouri',
 '54085': 'Ritchie County, West Virginia',
 '06065': 'Riverside County, California',
 '47145': 'Roane County, Tennessee',
 '54087': 'Roane County, West Virginia',
 '51161': 'Roanoke County, Virginia',
 '51770': 'Roanoke city, Virginia',
 '46109': 'Roberts County, South Dakota',
 '48393': 'Roberts County, Texas',
 '21201': 'Robertson County, Kentucky',
 '47147': 'Robertson County, Tennessee',
 '48395': 'Robertson County, Texas',
 '37155': 'Robeson County, North Carolina',
 '27133': 'Rock County, Minnesota',
 '31149': 'Rock County, Nebraska',
 '55105': 'Rock County, Wisconsin',
 '17161': 'Rock Island County, Illinois',
 '51163': 'Rockbridge County, Virginia',
 '21203': 'Rockcastle County, Kentucky',
 '13247': 'Rockdale County, Georgia',
 '33015': 'Rockingham County, New Hampshire',
 '37157': 'Rockingham County, North Carolina',
 '51165': 'Rockingham County, Virginia',
 '36087': 'Rockland County, New York',
 '48397': 'Rockwall County, Texas',
 '40129': 'Roger Mills County, Oklahoma',
 '40131': 'Rogers County, Oklahoma',
 '38079': 'Rolette County, North Dakota',
 '20163': 'Rooks County, Kansas',
 '30085': 'Roosevelt County, Montana',
 '35041': 'Roosevelt County, New Mexico',
 '26143': 'Roscommon County, Michigan',
 '27135': 'Roseau County, Minnesota',
 '30087': 'Rosebud County, Montana',
 '39141': 'Ross County, Ohio',
 '08107': 'Routt County, Colorado',
 '21205': 'Rowan County, Kentucky',
 '37159': 'Rowan County, North Carolina',
 '48399': 'Runnels County, Texas',
 '18139': 'Rush County, Indiana',
 '20165': 'Rush County, Kansas',
 '48401': 'Rusk County, Texas',
 '55107': 'Rusk County, Wisconsin',
 '01113': 'Russell County, Alabama',
 '20167': 'Russell County, Kansas',
 '21207': 'Russell County, Kentucky',
 '51167': 'Russell County, Virginia',
 '37161': 'Rutherford County, North Carolina',
 '47149': 'Rutherford County, Tennessee',
 '50021': 'Rutland County, Vermont',
 '48403': 'Sabine County, Texas',
 '22085': 'Sabine Parish, Louisiana',
 '19161': 'Sac County, Iowa',
 '06067': 'Sacramento County, California',
 '23023': 'Sagadahoc County, Maine',
 '26145': 'Saginaw County, Michigan',
 '08109': 'Saguache County, Colorado',
 '34033': 'Salem County, New Jersey',
 '51775': 'Salem city, Virginia',
 '05125': 'Saline County, Arkansas',
 '17165': 'Saline County, Illinois',
 '20169': 'Saline County, Kansas',
 '29195': 'Saline County, Missouri',
 '31151': 'Saline County, Nebraska',
 '49035': 'Salt Lake County, Utah',
 '45081': 'Saluda County, South Carolina',
 '37163': 'Sampson County, North Carolina',
 '48405': 'San Augustine County, Texas',
 '06069': 'San Benito County, California',
 '06071': 'San Bernardino County, California',
 '06073': 'San Diego County, California',
 '06075': 'San Francisco County, California',
 '48407': 'San Jacinto County, Texas',
 '06077': 'San Joaquin County, California',
 '08111': 'San Juan County, Colorado',
 '35045': 'San Juan County, New Mexico',
 '49037': 'San Juan County, Utah',
 '53055': 'San Juan County, Washington',
 '06079': 'San Luis Obispo County, California',
 '06081': 'San Mateo County, California',
 '08113': 'San Miguel County, Colorado',
 '35047': 'San Miguel County, New Mexico',
 '48409': 'San Patricio County, Texas',
 '48411': 'San Saba County, Texas',
 '46111': 'Sanborn County, South Dakota',
 '30089': 'Sanders County, Montana',
 '35043': 'Sandoval County, New Mexico',
 '39143': 'Sandusky County, Ohio',
 '17167': 'Sangamon County, Illinois',
 '26151': 'Sanilac County, Michigan',
 '49039': 'Sanpete County, Utah',
 '06083': 'Santa Barbara County, California',
 '06085': 'Santa Clara County, California',
 '04023': 'Santa Cruz County, Arizona',
 '06087': 'Santa Cruz County, California',
 '35049': 'Santa Fe County, New Mexico',
 '12113': 'Santa Rosa County, Florida',
 '12115': 'Sarasota County, Florida',
 '36091': 'Saratoga County, New York',
 '38081': 'Sargent County, North Dakota',
 '31153': 'Sarpy County, Nebraska',
 '55111': 'Sauk County, Wisconsin',
 '31155': 'Saunders County, Nebraska',
 '55113': 'Sawyer County, Wisconsin',
 '36093': 'Schenectady County, New York',
 '48413': 'Schleicher County, Texas',
 '13249': 'Schley County, Georgia',
 '36095': 'Schoharie County, New York',
 '26153': 'Schoolcraft County, Michigan',
 '17169': 'Schuyler County, Illinois',
 '29197': 'Schuyler County, Missouri',
 '36097': 'Schuyler County, New York',
 '42107': 'Schuylkill County, Pennsylvania',
 '39145': 'Scioto County, Ohio',
 '29199': 'Scotland County, Missouri',
 '37165': 'Scotland County, North Carolina',
 '05127': 'Scott County, Arkansas',
 '17171': 'Scott County, Illinois',
 '18143': 'Scott County, Indiana',
 '19163': 'Scott County, Iowa',
 '20171': 'Scott County, Kansas',
 '21209': 'Scott County, Kentucky',
 '27139': 'Scott County, Minnesota',
 '28123': 'Scott County, Mississippi',
 '29201': 'Scott County, Missouri',
 '47151': 'Scott County, Tennessee',
 '51169': 'Scott County, Virginia',
 '31157': 'Scotts Bluff County, Nebraska',
 '13251': 'Screven County, Georgia',
 '48415': 'Scurry County, Texas',
 '05129': 'Searcy County, Arkansas',
 '05131': 'Sebastian County, Arkansas',
 '08115': 'Sedgwick County, Colorado',
 '20173': 'Sedgwick County, Kansas',
 '12117': 'Seminole County, Florida',
 '13253': 'Seminole County, Georgia',
 '40133': 'Seminole County, Oklahoma',
 '36099': 'Seneca County, New York',
 '39147': 'Seneca County, Ohio',
 '47153': 'Sequatchie County, Tennessee',
 '40135': 'Sequoyah County, Oklahoma',
 '05133': 'Sevier County, Arkansas',
 '47155': 'Sevier County, Tennessee',
 '49041': 'Sevier County, Utah',
 '20175': 'Seward County, Kansas',
 '31159': 'Seward County, Nebraska',
 '48417': 'Shackelford County, Texas',
 '29203': 'Shannon County, Missouri',
 '28125': 'Sharkey County, Mississippi',
 '05135': 'Sharp County, Arkansas',
 '06089': 'Shasta County, California',
 '55115': 'Shawano County, Wisconsin',
 '20177': 'Shawnee County, Kansas',
 '55117': 'Sheboygan County, Wisconsin',
 '01117': 'Shelby County, Alabama',
 '17173': 'Shelby County, Illinois',
 '18145': 'Shelby County, Indiana',
 '19165': 'Shelby County, Iowa',
 '21211': 'Shelby County, Kentucky',
 '29205': 'Shelby County, Missouri',
 '39149': 'Shelby County, Ohio',
 '47157': 'Shelby County, Tennessee',
 '48419': 'Shelby County, Texas',
 '51171': 'Shenandoah County, Virginia',
 '27141': 'Sherburne County, Minnesota',
 '20179': 'Sheridan County, Kansas',
 '30091': 'Sheridan County, Montana',
 '31161': 'Sheridan County, Nebraska',
 '38083': 'Sheridan County, North Dakota',
 '56033': 'Sheridan County, Wyoming',
 '20181': 'Sherman County, Kansas',
 '31163': 'Sherman County, Nebraska',
 '41055': 'Sherman County, Oregon',
 '48421': 'Sherman County, Texas',
 '26155': 'Shiawassee County, Michigan',
 '16079': 'Shoshone County, Idaho',
 '27143': 'Sibley County, Minnesota',
 '06091': 'Sierra County, California',
 '35051': 'Sierra County, New Mexico',
 '30093': 'Silver Bow County, Montana',
 '21213': 'Simpson County, Kentucky',
 '28127': 'Simpson County, Mississippi',
 '19167': 'Sioux County, Iowa',
 '31165': 'Sioux County, Nebraska',
 '38085': 'Sioux County, North Dakota',
 '06093': 'Siskiyou County, California',
 '02220': 'Sitka City and Borough, Alaska',
 '53057': 'Skagit County, Washington',
 '02230': 'Skagway Municipality, Alaska',
 '53059': 'Skamania County, Washington',
 '38087': 'Slope County, North Dakota',
 '20183': 'Smith County, Kansas',
 '28129': 'Smith County, Mississippi',
 '47159': 'Smith County, Tennessee',
 '48423': 'Smith County, Texas',
 '51173': 'Smyth County, Virginia',
 '53061': 'Snohomish County, Washington',
 '42109': 'Snyder County, Pennsylvania',
 '35053': 'Socorro County, New Mexico',
 '06095': 'Solano County, California',
 '23025': 'Somerset County, Maine',
 '24039': 'Somerset County, Maryland',
 '34035': 'Somerset County, New Jersey',
 '42111': 'Somerset County, Pennsylvania',
 '48425': 'Somervell County, Texas',
 '06097': 'Sonoma County, California',
 '05001': 'Arkansas County, Arkansas',
 '51013': 'Arlington County, Virginia',
 '42005': 'Armstrong County, Pennsylvania',
 '48011': 'Armstrong County, Texas',
 '23003': 'Aroostook County, Maine',
 '31005': 'Arthur County, Nebraska',
 '22005': 'Ascension Parish, Louisiana',
 '37009': 'Ashe County, North Carolina',
 '39005': 'Ashland County, Ohio',
 '55003': 'Ashland County, Wisconsin',
 '05003': 'Ashley County, Arkansas',
 '39007': 'Ashtabula County, Ohio',
 '53003': 'Asotin County, Washington',
 '22007': 'Assumption Parish, Louisiana',
 '48013': 'Atascosa County, Texas',
 '20005': 'Atchison County, Kansas',
 '29005': 'Atchison County, Missouri',
 '39009': 'Athens County, Ohio',
 '13003': 'Atkinson County, Georgia',
 '34001': 'Atlantic County, New Jersey',
 '40005': 'Atoka County, Oklahoma',
 '28007': 'Attala County, Mississippi',
 '29007': 'Audrain County, Missouri',
 '19009': 'Audubon County, Iowa',
 '39011': 'Auglaize County, Ohio',
 '51015': 'Augusta County, Virginia',
 '46003': 'Aurora County, South Dakota',
 '48015': 'Austin County, Texas',
 '01001': 'Autauga County, Alabama',
 '37011': 'Avery County, North Carolina',
 '22009': 'Avoyelles Parish, Louisiana',
 '08009': 'Baca County, Colorado',
 '13005': 'Bacon County, Georgia',
 '48017': 'Bailey County, Texas',
 '12003': 'Baker County, Florida',
 '13007': 'Baker County, Georgia',
 '41001': 'Baker County, Oregon',
 '01003': 'Baldwin County, Alabama',
 '13009': 'Baldwin County, Georgia',
 '21007': 'Ballard County, Kentucky',
 '24005': 'Baltimore County, Maryland',
 '24510': 'Baltimore city, Maryland',
 '45009': 'Bamberg County, South Carolina',
 '48019': 'Bandera County, Texas',
 '13011': 'Banks County, Georgia',
 '31007': 'Banner County, Nebraska',
 '16005': 'Bannock County, Idaho',
 '26013': 'Baraga County, Michigan',
 '20007': 'Barber County, Kansas',
 '01005': 'Barbour County, Alabama',
 '54001': 'Barbour County, West Virginia',
 '38003': 'Barnes County, North Dakota',
 '25001': 'Barnstable County, Massachusetts',
 '45011': 'Barnwell County, South Carolina',
 '21009': 'Barren County, Kentucky',
 '55005': 'Barron County, Wisconsin',
 '13013': 'Barrow County, Georgia',
 '26015': 'Barry County, Michigan',
 '29009': 'Barry County, Missouri',
 '18005': 'Bartholomew County, Indiana',
 '20009': 'Barton County, Kansas',
 '29011': 'Barton County, Missouri',
 '13015': 'Bartow County, Georgia',
 '48021': 'Bastrop County, Texas',
 '29013': 'Bates County, Missouri',
 '21011': 'Bath County, Kentucky',
 '51017': 'Bath County, Virginia',

In [21]:
data['09009']

'New Haven County, Connecticut'

In [22]:
df_county_list = df = pd.DataFrame([
    {'FIPS': k, 'County': v.rsplit(',', 1)[0], 'State': v.rsplit(',', 1)[1].strip()}
    for k, v in data.items()
])

In [23]:
df_county_list.shape[0]

3143

In [26]:
# filling in counties missed by API
missing_locations = [
    {'FIPS': '02261', 'County': 'Valdez-Cordova Census Area', 'State': 'Alaska'},
    {'FIPS': '09110', 'County': 'Capitol Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09120', 'County': 'Greater Bridgeport Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09130', 'County': 'Greater Bridgeport Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09140', 'County': 'Greater Bridgeport Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09150', 'County': 'Northeastern Connecticut Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09160', 'County': 'Northwest Hills Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09170', 'County': 'South Central Connecticut Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09180', 'County': 'Southeastern Connecticut Planning Region', 'State': 'Connecticut'},
    {'FIPS': '09190', 'County': 'Western Connecticut Planning Region', 'State': 'Connecticut'},
    {'FIPS': '21179', 'County': 'Nelson County', 'State': 'Kentucky'},
    {'FIPS': '48219', 'County': 'Hockley County', 'State': 'Texas'}
]

for row in missing_locations:
    df_county_list.loc[len(df_county_list)] = row

In [27]:
df_county_list[df_county_list['FIPS'] == '02261']

       FIPS                      County   State
3143  02261  Valdez-Cordova Census Area  Alaska

In [28]:
for idx, row in df_county_list.iterrows():
    state = row['State']
    region = state_to_region.get(state)
    df_county_list.loc[idx, 'Region'] = region
df_county_list.tail()

       FIPS                                     County        State  Region
3150  09170  South Central Connecticut Planning Region  Connecticut     1.0
3151  09180   Southeastern Connecticut Planning Region  Connecticut     1.0
3152  09190        Western Connecticut Planning Region  Connecticut     1.0
3153  21179                              Nelson County     Kentucky     4.0
3154  48219                             Hockley County        Texas     6.0

In [29]:
df_county_list['Region'] = pd.to_numeric(df_county_list['Region']).astype('Int64')
df_county_list.head()

    FIPS            County        State  Region
0  09009  New Haven County  Connecticut       1
1  18035   Delaware County      Indiana       5
2  19055   Delaware County         Iowa       7
3  36025   Delaware County     New York       2
4  39041   Delaware County         Ohio       5

In [30]:
df_counties.head()

,Geography Type,Geography,FIPS,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,FIPS_clean
0,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18,09009
1,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21,09009
2,Counties,New Haven,9009,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20,09009
3,Counties,New Haven,9009,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21,09009
4,Counties,New Haven,9009,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18,09009

In [31]:
df_counties = pd.merge(df_counties, df_county_list, left_on=['FIPS_clean'], right_on = ['FIPS'], how = 'left')
df_counties.head()

,Geography Type,Geography,FIPS_x,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,FIPS_clean,FIPS_y,County,State,Region
0,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18,09009,09009,New Haven County,Connecticut,1
1,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21,09009,09009,New Haven County,Connecticut,1
2,Counties,New Haven,9009,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20,09009,09009,New Haven County,Connecticut,1
3,Counties,New Haven,9009,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21,09009,09009,New Haven County,Connecticut,1
4,Counties,New Haven,9009,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18,09009,09009,New Haven County,Connecticut,1

In [32]:
df_counties.shape[0]

21832

In [33]:
df_county_list.shape[0]

3155

In [34]:
df_county_list = df_county_list.drop_duplicates(subset='FIPS')

In [38]:
df_counties_unique = df_counties.drop_duplicates(subset='FIPS_clean')

df_county_list = pd.merge(
    df_county_list,
    df_counties_unique,
    left_on='FIPS',
    right_on='FIPS_clean',
    how='left'
)

In [39]:
df_county_list.head()

    FIPS            County        State  Region
0  09009  New Haven County  Connecticut       1
1  18035   Delaware County      Indiana       5
2  19055   Delaware County         Iowa       7
3  36025   Delaware County     New York       2
4  39041   Delaware County         Ohio       5

In [40]:
df_county.shape[0]

3153

In [222]:
try:
    insert_query = '''
    INSERT INTO fips_dim (
        state_territory, 
        county, 
        region, 
        original_geography_type, 
        original_geography,
        fips
    )
    VALUES (%s, %s, %s, %s, %s, %s)
    ON CONFLICT (original_geography, state_territory, county) DO NOTHING

    '''
    for index, row in df_county.iterrows():
        values = (
        row['State_y'] if pd.notna(row['State_y']) else None,
        row['County_y'] if pd.notna(row['County_y']) else None,
        row['Region_y'] if pd.notna(row['Region_y']) else None,
        row['Geography Type'] if pd.notna(row['Geography Type']) else None,
        row['Geography'] if pd.notna(row['Geography']) else None, 
        row['FIPS_clean'] if pd.notna(row['FIPS_clean']) else None
    )

        cursor.execute(insert_query,values)
    conn.commit()
    print(f"{len(df_county)} records inserted into geography_dim.")

except Exception as e:
    print(f"Error occurred: {e}")
    conn.rollback()

3153 records inserted into geography_dim.

In [41]:
df_counties.head()

,Geography Type,Geography,FIPS_x,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,FIPS_clean,FIPS_y,County,State,Region
0,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18,09009,09009,New Haven County,Connecticut,1
1,Counties,New Haven,9009,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21,09009,09009,New Haven County,Connecticut,1
2,Counties,New Haven,9009,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20,09009,09009,New Haven County,Connecticut,1
3,Counties,New Haven,9009,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21,09009,09009,New Haven County,Connecticut,1
4,Counties,New Haven,9009,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18,09009,09009,New Haven County,Connecticut,1

In [42]:
df_counties.drop(columns=['FIPS_x', 'FIPS_y'], inplace=True)
df_counties.head()

,Geography Type,Geography,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,FIPS_clean,County,State,Region
0,Counties,New Haven,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18,09009,New Haven County,Connecticut,1
1,Counties,New Haven,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21,09009,New Haven County,Connecticut,1
2,Counties,New Haven,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20,09009,New Haven County,Connecticut,1
3,Counties,New Haven,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21,09009,New Haven County,Connecticut,1
4,Counties,New Haven,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18,09009,New Haven County,Connecticut,1

In [43]:
cursor.execute("SELECT fips_id, original_geography, original_geography_type, fips FROM fips_dim")
mapping_data = cursor.fetchall()

fips_mapping = pd.DataFrame(mapping_data, columns=["fips_id", "original_geography", "original_geography_type", "fips"])
fips_mapping
fips_mapping['fips'] = pd.to_numeric(fips_mapping['fips']).astype('Int64')

In [44]:
fips_mapping['fips'] = pd.to_numeric(fips_mapping['fips']).astype('Int64')
fips_mapping

      fips_id         original_geography original_geography_type   fips
0           1                  New Haven                Counties   9009
1           2                   Delaware                Counties  18035
2           8                      Delta                Counties   8029
3          11             Denali Borough                Counties   2068
4          12                       Dent                Counties  29065
...       ...                        ...                     ...    ...
3157    12587   Northeastern Connecticut                Counties   9150
3158    12588            Northwest Hills                Counties   9160
3159    12589  South Central Connecticut                Counties   9170
3160    12590   Southeastern Connecticut                Counties   9180
3161    12591        Western Connecticut                Counties   9190

[3162 rows x 4 columns]

In [45]:
df_counties['FIPS_clean'] = df_counties['FIPS_clean'].astype('Int64')
df_counties = pd.merge(df_counties, fips_mapping, left_on=['FIPS_clean'], right_on = ['fips'], how = 'left')
print(df_counties.shape[0])
df_counties.head()

21832

,Geography Type,Geography,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,FIPS_clean,County,State,Region,fips_id,original_geography,original_geography_type,fips
0,Counties,New Haven,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18,9009,New Haven County,Connecticut,1,1,New Haven,Counties,9009
1,Counties,New Haven,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21,9009,New Haven County,Connecticut,1,1,New Haven,Counties,9009
2,Counties,New Haven,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20,9009,New Haven County,Connecticut,1,1,New Haven,Counties,9009
3,Counties,New Haven,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21,9009,New Haven County,Connecticut,1,1,New Haven,Counties,9009
4,Counties,New Haven,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18,9009,New Haven County,Connecticut,1,1,New Haven,Counties,9009

In [46]:
df_counties[df_counties['fips_id'].isna()]

Empty DataFrame
Columns: [Geography Type, Geography, Dimension Type, Dimension, Estimate (%), Sample Size, ci_lower, ci_upper, start_cohort_datetime, vaccine_id, FIPS_clean, County, State, Region, fips_id, original_geography, original_geography_type, fips]
Index: []

In [47]:
df_counties[df_counties['Geography'] == 'Valdez-Cordova Census Area']

,Geography Type,Geography,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,FIPS_clean,County,State,Region,fips_id,original_geography,original_geography_type,fips
20627,Counties,Valdez-Cordova Census Area,Age,>=18 Years,31.0,<NA>,29.4,32.8,2018-01-01,18,2261,Valdez-Cordova Census Area,Alaska,10,12582,Valdez-Cordova Census Area,Counties,2261
20628,Counties,Valdez-Cordova Census Area,Age,>=18 Years,36.8,<NA>,34.9,38.8,2019-01-01,19,2261,Valdez-Cordova Census Area,Alaska,10,12582,Valdez-Cordova Census Area,Counties,2261
20629,Counties,Valdez-Cordova Census Area,>=18 Years,Non-Medical Setting,40.3,<NA>,38.2,42.6,2018-01-01,18,2261,Valdez-Cordova Census Area,Alaska,10,12582,Valdez-Cordova Census Area,Counties,2261

In [49]:
df_counties.drop(columns=['County', 'State', 'Region', 'Geography Type', 'Geography', 'FIPS_clean', 'fips', 'original_geography', 'original_geography_type'], inplace=True)
df_counties.head()

,Dimension Type,Dimension,Estimate (%),Sample Size,ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id
0,>=18 Years,Non-Medical Setting,45.5,<NA>,43.9,47.2,2018-01-01,18,1
1,>=18 Years,Non-Medical Setting,53.0,<NA>,46.0,60.9,2021-01-01,21,1
2,Age,>=18 Years,52.4,<NA>,50.6,54.3,2020-01-01,20,1
3,Age,>=18 Years,50.2,<NA>,45.4,55.8,2021-01-01,21,1
4,Age,>=18 Years,34.0,<NA>,32.6,35.5,2018-01-01,18,1

In [52]:
df_counties.drop(columns=['Sample Size'], inplace=True)

In [53]:
df_counties.head()

,Dimension Type,Dimension,Estimate (%),ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id
0,>=18 Years,Non-Medical Setting,45.5,43.9,47.2,2018-01-01,18,1
1,>=18 Years,Non-Medical Setting,53.0,46.0,60.9,2021-01-01,21,1
2,Age,>=18 Years,52.4,50.6,54.3,2020-01-01,20,1
3,Age,>=18 Years,50.2,45.4,55.8,2021-01-01,21,1
4,Age,>=18 Years,34.0,32.6,35.5,2018-01-01,18,1

In [54]:
df_counties.shape[0]

21832

In [55]:
df_age = df_counties[df_counties['Dimension Type'] == 'Age']

In [56]:
df_age.rename(columns={'Dimension': 'Age'}, inplace=True)
df_age.drop(columns=['Dimension Type'], inplace=True)
print(df_age.shape[0])
df_age.head()

15623

/var/folders/jq/q12_1s5j0kx30cqlm76w1m740000gn/T/ipykernel_12858/3920806466.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age.rename(columns={'Dimension': 'Age'}, inplace=True)
/var/folders/jq/q12_1s5j0kx30cqlm76w1m740000gn/T/ipykernel_12858/3920806466.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age.drop(columns=['Dimension Type'], inplace=True)

,Age,Estimate (%),ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id
2,>=18 Years,52.4,50.6,54.3,2020-01-01,20,1
3,>=18 Years,50.2,45.4,55.8,2021-01-01,21,1
4,>=18 Years,34.0,32.6,35.5,2018-01-01,18,1
5,>=18 Years,49.5,47.8,51.3,2019-01-01,19,1
8,>=18 Years,27.2,25.7,29.0,2018-01-01,18,2

In [57]:
df_location = df_counties[df_counties['Dimension Type'] != 'Age']
df_location.head()

,Dimension Type,Dimension,Estimate (%),ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id
0,>=18 Years,Non-Medical Setting,45.5,43.9,47.2,2018-01-01,18,1
1,>=18 Years,Non-Medical Setting,53.0,46.0,60.9,2021-01-01,21,1
6,>=18 Years,Non-Medical Setting,41.8,39.0,44.7,2018-01-01,18,2
7,>=18 Years,Non-Medical Setting,41.1,32.7,49.7,2021-01-01,21,2
13,>=18 Years,Non-Medical Setting,44.0,32.5,55.7,2021-01-01,21,3149

In [58]:
cursor.execute("SELECT vaccine_location, vaccine_location_id FROM vaccine_location_dim")
mapping_data = cursor.fetchall()

vac_location = pd.DataFrame(mapping_data, columns=["vaccine_location", "vaccine_location_id"])
vac_location

      vaccine_location  vaccine_location_id
0  Non-Medical Setting                    1
1               School                    2
2       Pharmacy/Store                    3
3            Workplace                    4
4      Medical Setting                    5

In [59]:
# we merge df_children with the vaccine_dim
df_location = pd.merge(df_location, vac_location, left_on = ['Dimension'], right_on=['vaccine_location'], how='left')
df_location.head()

,Dimension Type,Dimension,Estimate (%),ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id,vaccine_location,vaccine_location_id
0,>=18 Years,Non-Medical Setting,45.5,43.9,47.2,2018-01-01,18,1,Non-Medical Setting,1
1,>=18 Years,Non-Medical Setting,53.0,46.0,60.9,2021-01-01,21,1,Non-Medical Setting,1
2,>=18 Years,Non-Medical Setting,41.8,39.0,44.7,2018-01-01,18,2,Non-Medical Setting,1
3,>=18 Years,Non-Medical Setting,41.1,32.7,49.7,2021-01-01,21,2,Non-Medical Setting,1
4,>=18 Years,Non-Medical Setting,44.0,32.5,55.7,2021-01-01,21,3149,Non-Medical Setting,1

In [60]:
df_location.drop(columns=['vaccine_location'], inplace=True)
df_location.head()

,Dimension Type,Dimension,Estimate (%),ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id,vaccine_location_id
0,>=18 Years,Non-Medical Setting,45.5,43.9,47.2,2018-01-01,18,1,1
1,>=18 Years,Non-Medical Setting,53.0,46.0,60.9,2021-01-01,21,1,1
2,>=18 Years,Non-Medical Setting,41.8,39.0,44.7,2018-01-01,18,2,1
3,>=18 Years,Non-Medical Setting,41.1,32.7,49.7,2021-01-01,21,2,1
4,>=18 Years,Non-Medical Setting,44.0,32.5,55.7,2021-01-01,21,3149,1

In [61]:
df_location.head()

,Dimension Type,Dimension,Estimate (%),ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id,vaccine_location_id
0,>=18 Years,Non-Medical Setting,45.5,43.9,47.2,2018-01-01,18,1,1
1,>=18 Years,Non-Medical Setting,53.0,46.0,60.9,2021-01-01,21,1,1
2,>=18 Years,Non-Medical Setting,41.8,39.0,44.7,2018-01-01,18,2,1
3,>=18 Years,Non-Medical Setting,41.1,32.7,49.7,2021-01-01,21,2,1
4,>=18 Years,Non-Medical Setting,44.0,32.5,55.7,2021-01-01,21,3149,1

In [62]:
df_age.head()

,Age,Estimate (%),ci_lower,ci_upper,start_cohort_datetime,vaccine_id,fips_id
2,>=18 Years,52.4,50.6,54.3,2020-01-01,20,1
3,>=18 Years,50.2,45.4,55.8,2021-01-01,21,1
4,>=18 Years,34.0,32.6,35.5,2018-01-01,18,1
5,>=18 Years,49.5,47.8,51.3,2019-01-01,19,1
8,>=18 Years,27.2,25.7,29.0,2018-01-01,18,2

In [64]:
# loading cumulative fact table
try:
    insert_query='''
    INSERT INTO influenza_transaction_fact(
        age,
        influenza_transaction_estimate_pct,
        influenza_transaction_ci_lower,
        influenza_transaction_ci_upper,
        influenza_transaction_survey_datetime,
        influenza_transaction_vaccine_id,
        influenza_transaction_fips_id
    )
    VALUES(%s, %s, %s, %s, %s, %s, %s)
    '''
    for index, row in df_age.iterrows():
        start_cohort_date = pd.to_datetime(row['start_cohort_datetime']).date() if pd.notnull(row['start_cohort_datetime']) else None
        vaccine_id = int(row['vaccine_id']) if pd.notnull(row['vaccine_id']) else None
        fips_id = int(row['fips_id']) if pd.notnull(row['fips_id']) else None

        cursor.execute(insert_query,(
        row['Age'],
        row['Estimate (%)'],
        row['ci_lower'],
        row['ci_upper'],
        start_cohort_date,
        vaccine_id,
        fips_id
        ))
    conn.commit()
    print(f"{len(df_age)} records inserted into influenza_transaction_fact.")

except Exception as e:
    print(f"Error occurred: {e}")
    traceback.print_exc(file=sys.stdout)
    conn.rollback()

15623 records inserted into influenza_transaction_fact.

In [67]:
# loading cumulative fact table
try:
    insert_query='''
    INSERT INTO influenza_transaction_fact(
        age,
        influenza_transaction_estimate_pct,
        influenza_transaction_ci_lower,
        influenza_transaction_ci_upper,
        influenza_transaction_survey_datetime,
        influenza_transaction_vaccine_id,
        influenza_transaction_fips_id,
        influenza_transaction_location_id
    )
    VALUES(%s, %s, %s, %s, %s, %s, %s, %s)
    '''
    for index, row in df_location.iterrows():
        start_cohort_date = pd.to_datetime(row['start_cohort_datetime']).date() if pd.notnull(row['start_cohort_datetime']) else None
        vaccine_id = int(row['vaccine_id']) if pd.notnull(row['vaccine_id']) else None
        fips_id = int(row['fips_id']) if pd.notnull(row['fips_id']) else None
        vaccine_location_id = int(row['vaccine_location_id']) if pd.notnull(row['vaccine_location_id']) else None

        cursor.execute(insert_query,(
        row['Dimension Type'],
        row['Estimate (%)'],
        row['ci_lower'],
        row['ci_upper'],
        start_cohort_date,
        vaccine_id,
        fips_id,
        vaccine_location_id
        ))
    conn.commit()
    print(f"{len(df_age)} records inserted into influenza_transaction_fact.")

except Exception as e:
    print(f"Error occurred: {e}")
    traceback.print_exc(file=sys.stdout)
    conn.rollback()

15623 records inserted into influenza_transaction_fact.